# Site
name: "Mehrdad Mohammadian"
title: "Mehrdad Mohammadian"
short_description: "Let's Develop!"
description: "
Let's Develop!
Personal Website
Mehrdad Mohammadian | مهرداد محمدیان
"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
url: mehrdad-dev.github.io
baseurl: ''
# google_analytics: "UA-xxxxxxxx-1"
disqus: "https-www-mehrdad-dev-github-io"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:categories/:title/
formspree: mzbjjnev
email: dev.mehrdad@gmail.com


authors:
  mehrdad:
    name: Mehrdad Mohammadian
    display_name: mehrdad.dev
    gravatar: 07c053a3c1a74394655df999914c666b # gravatar hash
    email: dev.mehrdad@gmail.com
    web: https://www.mehrdad-dev.github.io
    twitter: https://twitter.com/mehrdad_dev
    instagram: https://instagram.com/mehrdad.dev
    linkedin: https://www.linkedin.com/in/mehrdad-mohammadian-
    github: https://github.com/mehrdad-dev
    description: "Mehrdad Mohammadian | مهرداد محمدیان"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
